export enum RegisterTypes {
    START = 'REGISTER/REGISTER__START',
    PROCESS = 'REGISTER/REGISTER__PROCESS',
    END = 'REGISTER/REGISTER__END',
    ERROR = 'REGISTER/REGISTER__ERROR',
    RESET = 'REGISTER/REGISTER__RESET'
}