export enum LogoutTypes {
    START = 'LOGOUT/LOGOUT__START',
    PROCESS = 'LOGOUT/LOGOUT__PROCESS',
    END = 'LOGOUT/LOGOUT__END',
    ERROR = 'LOGOUT/LOGOUT__ERROR',
    RESET = 'LOGOUT/LOGOUT__RESET'
}