export enum UpdaterTypes {
    START = 'UPDATE/UPDATE__START',
    PROCESS = 'UPDATE/UPDATE__PROCESS',
    END = 'UPDATE/UPDATE__END',
    ERROR = 'UPDATE/UPDATE__ERROR',
    RESET = 'UPDATE/UPDATE__RESET'
}