export enum BootCampsTypes{
    START = 'BOOT__CAMPS/BOOT__CAMPS__START',
    PROCESS = 'BOOT__CAMPS/BOOT__CAMPS__PROCESS',
    END = 'BOOT__CAMPS/BOOT__CAMPS__END',
    ERROR = 'BOOT__CAMPS/BOOT__CAMPS__ERROR',
    RESET = 'BOOT__CAMPS/BOOT__CAMPS__RESET',
}