export enum LoginTypes {
    START = 'LOGIN/LOGIN__START',
    PROCESS = 'LOGIN/LOGIN__PROCESS',
    END = 'LOGIN/LOGIN__END',
    ERROR = 'LOGIN/LOGIN__ERROR',
    RESET = 'LOGIN/LOGIN__RESET',
    IS__COMPLETE = 'LOGIN/ IS__COMPLETE'
}
